In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Zomato-data-.csv")
df.head(7)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
5,Timepass Dinner,Yes,No,3.8/5,286,600,Buffet
6,Rosewood International Hotel - Bar & Restaurant,No,No,3.6/5,8,800,Buffet

In [ ]:
df.tail()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [ ]:
df.sample(4)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
8,Penthouse Cafe,Yes,No,4.0/5,324,700,other
106,Spice 9,No,No,3.4/5,8,300,Dining
11,Cafe Shuffle,Yes,Yes,4.2/5,150,600,Cafes
45,Hotboxit,No,No,3.8/5,36,400,Dining

In [ ]:
df.shape

(148, 7)

In [ ]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [ ]:
df.dtypes['approx_cost(for two people)']

dtype('int64')

In [ ]:
df['approx_cost(for two people)'].describe()

count    148.000000
mean     418.243243
std      223.085098
min      100.000000
25%      200.000000
50%      400.000000
75%      600.000000
max      950.000000
Name: approx_cost(for two people), dtype: float64

In [ ]:
df[["name", "online_order"]] # selecting multiple

                 Rest_name online_order
0                    Jalsa          Yes
1           Spice Elephant          Yes
2          San Churro Cafe          Yes
3    Addhuri Udupi Bhojana           No
4            Grand Village           No
..                     ...          ...
143       Melting Melodies           No
144        New Indraprasta           No
145           Anna Kuteera          Yes
146                 Darbar           No
147          Vijayalakshmi          Yes

[148 rows x 2 columns]

In [ ]:
df.iloc[0] #selecting one row

name                            Jalsa
online_order                      Yes
book_table                        Yes
rate                            4.1/5
votes                             775
approx_cost(for two people)       800
listed_in(type)                Buffet
Name: 0, dtype: object

In [ ]:
df.iloc[:3] #first 3 rows

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet

In [ ]:
df.iloc[2:5,1:3] #rows and column

  online_order book_table
2          Yes         No
3           No         No
4           No         No

In [ ]:
df.sort_values("votes") #ascending order

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
110,Hari Super Sandwich,No,No,3.2/5,0,200,Dining
107,Coffee Shopee,No,No,3.4/5,0,250,Dining
117,Kulfi & More,No,No,3.4/5,0,150,Dining
118,Kannadigas Karavali,No,No,3.4/5,0,250,Dining
116,Wood Stove,No,No,3.4/5,0,150,Dining
...,...,...,...,...,...,...,...
65,Kabab Magic,Yes,No,4.1/5,1720,400,Dining
44,Onesta,Yes,Yes,4.6/5,2556,600,other
7,Onesta,Yes,Yes,4.6/5,2556,600,Cafes
86,Meghana Foods,Yes,No,4.4/5,4401,600,Dining
38,Empire Restaurant,Yes,No,4.4/5,4884,750,other

In [ ]:
df.sort_values("votes",ascending=False) #desending order

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
38,Empire Restaurant,Yes,No,4.4/5,4884,750,other
86,Meghana Foods,Yes,No,4.4/5,4401,600,Dining
7,Onesta,Yes,Yes,4.6/5,2556,600,Cafes
44,Onesta,Yes,Yes,4.6/5,2556,600,other
65,Kabab Magic,Yes,No,4.1/5,1720,400,Dining
...,...,...,...,...,...,...,...
140,Darkolates,No,No,3.3/5,0,200,Dining
143,Melting Melodies,No,No,3.3/5,0,100,Dining
142,Gawdaru Mane Beriyani,No,No,3.3/5,0,300,Dining
141,Swaada Healthy Kitchen,No,No,3.3/5,0,350,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining

In [ ]:
df.sort_values(["votes","approx_cost(for two people)"])

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
84,Chill Out,No,No,3.8/5,0,100,Dining
131,Foodlieious Multi Cuisine,No,No,3.4/5,0,100,Dining
143,Melting Melodies,No,No,3.3/5,0,100,Dining
72,Spicy Tandoor,No,No,4.1/5,0,150,Dining
113,Dharwad Line Bazaar Mishra Pedha,No,No,3.4/5,0,150,Dining
...,...,...,...,...,...,...,...
65,Kabab Magic,Yes,No,4.1/5,1720,400,Dining
7,Onesta,Yes,Yes,4.6/5,2556,600,Cafes
44,Onesta,Yes,Yes,4.6/5,2556,600,other
86,Meghana Foods,Yes,No,4.4/5,4401,600,Dining
38,Empire Restaurant,Yes,No,4.4/5,4884,750,other

In [ ]:
df["revenue"]=df["votes"]*df["approx_cost(for two people)"] #adding new column
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type),revenue
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet,620000
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet,629600
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet,734400
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet,26400
4,Grand Village,No,No,3.8/5,166,600,Buffet,99600

In [ ]:
df.shape

(148, 8)

In [ ]:
df.rename(columns={"name":"Rest_name"}) #rename column

,Rest_name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type),revenue
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet,620000
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet,629600
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet,734400
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet,26400
4,Grand Village,No,No,3.8/5,166,600,Buffet,99600
...,...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining,0
144,New Indraprasta,No,No,3.3/5,0,150,Dining,0
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining,346950
146,Darbar,No,No,3.0/5,98,800,Dining,78400
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining,9400

In [ ]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type),revenue
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet,620000
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet,629600
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet,734400
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet,26400
4,Grand Village,No,No,3.8/5,166,600,Buffet,99600

In [ ]:
df.rename(columns={"name":"Rest_name"},inplace=True) #Permanent rest name

In [ ]:
df.rename(columns={"Rest_name":"Rest_Name"},inplace=True)

In [ ]:
df.head()

,Rest_Name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type),revenue
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet,620000
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet,629600
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet,734400
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet,26400
4,Grand Village,No,No,3.8/5,166,600,Buffet,99600

In [ ]:
df.drop("votes",axis=1) #Delete column

,Rest_Name,online_order,book_table,rate,approx_cost(for two people),listed_in(type),revenue
0,Jalsa,Yes,Yes,4.1/5,800,Buffet,620000
1,Spice Elephant,Yes,No,4.1/5,800,Buffet,629600
2,San Churro Cafe,Yes,No,3.8/5,800,Buffet,734400
3,Addhuri Udupi Bhojana,No,No,3.7/5,300,Buffet,26400
4,Grand Village,No,No,3.8/5,600,Buffet,99600
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,100,Dining,0
144,New Indraprasta,No,No,3.3/5,150,Dining,0
145,Anna Kuteera,Yes,No,4.0/5,450,Dining,346950
146,Darbar,No,No,3.0/5,800,Dining,78400
147,Vijayalakshmi,Yes,No,3.9/5,200,Dining,9400

In [ ]:
df.head()

,Rest_Name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type),revenue
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet,620000
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet,629600
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet,734400
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet,26400
4,Grand Village,No,No,3.8/5,166,600,Buffet,99600

In [ ]:
df.drop("votes",axis=1,inplace=True) #permanent delete column

In [ ]:
df.head()

,Rest_Name,online_order,book_table,rate,approx_cost(for two people),listed_in(type),revenue
0,Jalsa,Yes,Yes,4.1/5,800,Buffet,620000
1,Spice Elephant,Yes,No,4.1/5,800,Buffet,629600
2,San Churro Cafe,Yes,No,3.8/5,800,Buffet,734400
3,Addhuri Udupi Bhojana,No,No,3.7/5,300,Buffet,26400
4,Grand Village,No,No,3.8/5,600,Buffet,99600

In [ ]:
df.drop(3) # delete row 3

,Rest_Name,online_order,book_table,rate,approx_cost(for two people),listed_in(type),revenue
0,Jalsa,Yes,Yes,4.1/5,800,Buffet,620000
1,Spice Elephant,Yes,No,4.1/5,800,Buffet,629600
2,San Churro Cafe,Yes,No,3.8/5,800,Buffet,734400
4,Grand Village,No,No,3.8/5,600,Buffet,99600
5,Timepass Dinner,Yes,No,3.8/5,600,Buffet,171600
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,100,Dining,0
144,New Indraprasta,No,No,3.3/5,150,Dining,0
145,Anna Kuteera,Yes,No,4.0/5,450,Dining,346950
146,Darbar,No,No,3.0/5,800,Dining,78400
147,Vijayalakshmi,Yes,No,3.9/5,200,Dining,9400

In [ ]:
df.head()

,Rest_Name,online_order,book_table,rate,approx_cost(for two people),listed_in(type),revenue
0,Jalsa,Yes,Yes,4.1/5,800,Buffet,620000
1,Spice Elephant,Yes,No,4.1/5,800,Buffet,629600
2,San Churro Cafe,Yes,No,3.8/5,800,Buffet,734400
3,Addhuri Udupi Bhojana,No,No,3.7/5,300,Buffet,26400
4,Grand Village,No,No,3.8/5,600,Buffet,99600

In [ ]:
df.isnull() # missing value

,Rest_Name,online_order,book_table,rate,approx_cost(for two people),listed_in(type),revenue
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
143,False,False,False,False,False,False,False
144,False,False,False,False,False,False,False
145,False,False,False,False,False,False,False
146,False,False,False,False,False,False,False
147,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum() #count of missing value

Rest_Name                      0
online_order                   0
book_table                     0
rate                           0
approx_cost(for two people)    0
listed_in(type)                0
revenue                        0
dtype: int64

In [ ]:
df.dropna() # remove missing value

,Rest_Name,online_order,book_table,rate,approx_cost(for two people),listed_in(type),revenue
0,Jalsa,Yes,Yes,4.1/5,800,Buffet,620000
1,Spice Elephant,Yes,No,4.1/5,800,Buffet,629600
2,San Churro Cafe,Yes,No,3.8/5,800,Buffet,734400
3,Addhuri Udupi Bhojana,No,No,3.7/5,300,Buffet,26400
4,Grand Village,No,No,3.8/5,600,Buffet,99600
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,100,Dining,0
144,New Indraprasta,No,No,3.3/5,150,Dining,0
145,Anna Kuteera,Yes,No,4.0/5,450,Dining,346950
146,Darbar,No,No,3.0/5,800,Dining,78400
147,Vijayalakshmi,Yes,No,3.9/5,200,Dining,9400

In [ ]:
df["votes"].fillna(df["votes"].mean(),inplace=True) #

/tmp/ipykernel_1709/1249268406.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["votes"].fillna(df["votes"].mean(),inplace=True)

In [ ]:
df["votes"].fillna(df["votes"].median(),inplace=True)

/tmp/ipykernel_1709/888035304.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["votes"].fillna(df["votes"].median(),inplace=True)

In [ ]:
df.fillna(0,inplace=True) #permanent fill missing

In [ ]:
df.duplicated() #Duplicate values

0      False
1      False
2      False
3      False
4      False
       ...
143    False
144    False
145    False
146    False
147    False
Length: 148, dtype: bool

In [ ]:
df.duplicated().sum() #count of duplicate value

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True) #remove duplicates

In [ ]:
df["name"].unique() #unique

array(['Jalsa', 'Spice Elephant', 'San Churro Cafe',
       'Addhuri Udupi Bhojana', 'Grand Village', 'Timepass Dinner',
       'Rosewood International Hotel - Bar & Restaurant', 'Onesta',
       'Penthouse Cafe', 'Smacznego', 'Village Café', 'Cafe Shuffle',
       'The Coffee Shack', 'Caf-Eleven', 'Cafe Vivacity', 'Catch-up-ino',
       "Kirthi's Biryani", 'T3H Cafe', '360 Atoms Restaurant And Cafe',
       'The Vintage Cafe', 'Woodee Pizza', 'Cafe Coffee Day',
       'My Tea House', 'Hide Out Cafe', 'CAFE NOVA', 'Coffee Tindi',
       'Sea Green Cafe', 'Cuppa', "Srinathji's Cafe", 'Redberrys',
       'Foodiction', 'Sweet Truth', 'Ovenstory Pizza', 'Faasos',
       'Behrouz Biryani', 'Fast And Fresh', 'Szechuan Dragon',
       'Empire Restaurant', 'Maruthi Davangere Benne Dosa', 'Chaatimes',
       'Havyaka Mess', "McDonald's", "Domino's Pizza", 'Hotboxit',
       'Kitchen Garden', 'Recipe', 'Beijing Bites', 'Tasty Bytes',
       'Petoo', 'Shree Cool Point', 'Corner House Ice Cream',
       'Biryanis And More', 'Roving Feast', 'FreshMenu',
       'Banashankari Donne Biriyani', 'Wamama', 'Five Star Chicken',
       'XO Belgian Waffle', 'Peppy Peppers', 'Goa 0 Km',
       'Chinese Kitchen', 'Jeet Restaurant', 'Cake of the Day',
       'Kabab Magic', "Namma Brahmin's Idli", 'Gustoes Beer House',
       'Sugar Rush', 'Burger King', 'The Good Bowl', 'The Biryani Cafe',
       'Spicy Tandoor', 'LSD Cafe', 'Rolls On Wheels',
       'Om Sri Vinayaka Chats',
       'Sri Guru Kottureshwara Davangere Benne Dosa',
       'Devanna Dum Biriyani Centre', 'Kolbeh', 'Upahar Sagar',
       'Kadalu Sea Food Restaurant', 'Frozen Bottle', 'Parimala Sweets',
       'Vaishali Deluxe', 'Chill Out', 'The Big O Bakes', 'Meghana Foods',
       'Krishna Sagar', 'Dessert Rose', 'Chickpet Donne Biryani House',
       'Me And My Cake', 'Sunsadm', 'Annapooraneshwari Mess',
       "Thanco's Natural Ice Creams", 'Nandhini Deluxe',
       "Vi Ra's Bar and Restaurant", 'Kaggis', 'Ayda Persian Kitchen',
       'Chatar Patar', 'Polar Bear', "Kidambi's Kitchen", 'Mane Thindi',
       'Kotian Karavali Restaurant', 'Floured-Baked With Love',
       'Cakes & Slices', 'Spice 9', 'Coffee Shopee',
       'Naveen Kabab & Biriyani Mane', 'Katriguppe Donne Biryani',
       'Hari Super Sandwich', 'Atithi Point Ande Ka Funda', 'Just Bake',
       'Dharwad Line Bazaar Mishra Pedha', 'Cake Bite',
       "Aarush's Food Plaza", 'Wood Stove', 'Kulfi & More',
       'Kannadigas Karavali', 'K27 - The Pub', 'Bengaluru Coffee House',
       'New Mangalore Lunch Home', 'Coffee Bytes', 'Parjanya Chat Zone',
       "Kwality Wall's Swirl's Happiness Station", 'Soms Kitchen & Bakes',
       'Banashankari Nati Style', 'Ruchi Maayaka', 'Mohitesh Hut Roll',
       'Sri Basaveshwar Jolada Rotti Oota', 'Roll Magic Fast Food',
       'Foodlieious Multi Cuisine', 'Thanishka Nati And Karavali Style',
       'Swathi Cool Point', 'Kaumudis Juoice', 'Amma - Manae',
       'Sri Sai Tiffannies', 'Hotel Andhra Speices',
       'Sri Murari Family Restaurant', 'Aramane Donne Biriyani',
       'Darkolates', 'Swaada Healthy Kitchen', 'Gawdaru Mane Beriyani',
       'Melting Melodies', 'New Indraprasta', 'Anna Kuteera', 'Darbar',
       'Vijayalakshmi'], dtype=object)

In [ ]:
df["name"].nunique() #count of unique value

145

In [ ]:
df.groupby("votes")["approx_cost(for two people)"].mean()

votes
0       239.393939
4       400.000000
6       300.000000
7       350.000000
8       400.000000
           ...
1647    600.000000
1720    400.000000
2556    600.000000
4401    600.000000
4884    750.000000
Name: approx_cost(for two people), Length: 90, dtype: float64